### ISSUE TITLE
Does this work in Python 3?

### ISSUE THREAD

**Issue by saideep-g** [xamiel/pydf2json#6]
I was getting errors while using in Python 3.5. Does this work in Python 3?

**Comment by kingaling** [comment]
No it doesn't. Sorry about that. It works on Python 2.7. This is mentioned in the setup.py file but I should probably put that in a more prominent place.

**Comment by madprogramer** [comment]
https://www.python.org/doc/sunset-python-2/

Though obscure, pydf2json is still a very useful package that I still find useful . If you do not plan for a Python 3 conversion yourself, I would be interested in forking it!

**Comment by kingaling** [comment]
@madprogramer  
I keep telling myself I'm gonna convert for python 3 and then I never do it. I would not be opposed if you wanna do it. :)
There is a more up to date branch (ReOrg) present that i will merge this week. The branch makes things a little more modular and has some fixes.
